windows:
  - name: RBR_config
    layout: main-vertical
    panes:
      - commands:
        - clear
        - echo "Configurations Windows"
      - commands:
        - clear
        - cd /Users/christopherhough/.myconfigurations
        - clear
      - commands:
        - clear
        - cd /Users/christopherhough/Career/RobotsBuildingRobots/code/personal-branding/MyVersionedAssets
        - clear
      - commands:
        - clear
        - cd /Users/christopherhough/Career/RobotsBuildingRobots/code/personal-branding/MyVersionedAssets
        - clear
      - commands:
        - clear
        - cd /Users/christopherhough
        - clear
        - lsa
