#!/bin/zsh
function msg() {
  echo
  echo "-------------------------------------------"
  echo $1
  echo "-------------------------------------------"
  echo
}
function help() {
  echo
  echo "-------------------------------------------"
  echo "  apphelp"
  echo "  githelp"
  echo "  herokuhelp"
  echo "  keybasehelp"
  echo "  rubyhelp"
  echo "  shellhelp"
  echo "-------------------------------------------"
  echo
}
