#!/bin/zsh

# Shell
source $HOME/.myconfigurations/workstation/shell/shortcuts/shell
# ---------------------------------------------------------------
# Ruby
source $HOME/.myconfigurations/workstation/shell/shortcuts/ruby
# ---------------------------------------------------------------
# Git
source $HOME/.myconfigurations/workstation/shell/shortcuts/git
# ---------------------------------------------------------------
# Heroku
source $HOME/.myconfigurations/workstation/shell/shortcuts/heroku
# ---------------------------------------------------------------
# Keybase
source $HOME/.myconfigurations/workstation/shell/shortcuts/keybase
# ---------------------------------------------------------------
# Applications
source $HOME/.myconfigurations/workstation/shell/shortcuts/apps
# ---------------------------------------------------------------
# PRIVATE CONFIGURATIONS
source $HOME/.myconfigurations/workstation/shell/shortcuts/private
