#!/bin/zsh
apphelp () {
  echo
  echo "--------------------------------------------------------------------------------"
  echo "  mc           = mailcatcher -f -v"
  echo "  atom         = atom ."
  echo "  dpg          = dotgpg alias for encryption"
  echo "  openmd       = open mou for passed in md file"
  echo "--------------------------------------------------------------------------------"
  echo
}
