#!/bin/zsh
apphelp () {
  echo
  echo "-------------------------------------------"
  echo "  mc           = mailcatcher -f -v"
  echo "  atom         = atom ."
  echo "-------------------------------------------"
  echo
}
