#!/bin/zsh
dockerhelp () {
  echo
  echo "--------------------------------------------------------------------------------"
  echo "  dk            = base command"
  echo "  dkc           = docker compose base command"
  echo "  dkl           = list containers"
  echo "  dkcs          = use docker compose to list all services"
  echo "  dkcl          = use docker compose to show logs"
  echo "  dkclf         = use docker compose to follow logs"
  echo "  dks           = stop container"
  echo "  dku           = startup containers"
  echo "  dke           = searches for image name and attempts to connect via bash"
  echo "  dksa          = stop all containers"
  echo "  dkpa          = prune all containers"
  echo "  dkb           = build docker container"
  echo "  dks           = build docker and connect shell entry point"
  echo "--------------------------------------------------------------------------------"
  echo
}
