#!/bin/zsh
dockerhelp () {
  echo
  echo "--------------------------------------------------------------------------------"
  echo "  dk            = base command"
  echo "  dc            = docker compose base command"
  echo "  dkl           = list containers"
  echo "  dks           = stop container"
  echo "  dku           = startup containers"
  echo "  dke           = searches for image name and attempts to connect via bash"
  echo "  dksa          = stop all containers"
  echo "  dkpa          = prune all containers"
  echo "  db            = build docker container"
  echo "  ds            = build docker and connect shell entry point"
  echo "--------------------------------------------------------------------------------"
  echo
}
