#!/bin/zsh
githelp () {
  echo
  echo "--------------------------------------------------------------------------------"
  echo "  gc           = commit locally, but do not push to origin"
  echo "  gcb          = pull, create local branch, push it to origin, set upstream"




  echo "  gcbn         = current branch name"
  echo "--------------------------------------------------------------------------------"







  echo "  gfmb         = git flow subcommand finish branch :: param 1= subcommand param 2=branch"
  echo "  gfcb         = git flow subcommand start branch :: param 1= subcommand param 2=branch"
  echo "  gfi          = setup code repo using gitflow"
  echo "  gfh          = git flow help"
  echo "  gf           = git flow"
  echo "---------------------------------------------------------------"

  echo "  gcl          = git commit local, and status"
  echo "  gmdb         = git merge and delete branch everywhere"
  echo "  gp           = git pull"
  echo "  gpo          = git push to repo"
  echo "  gd           = git diff"
  echo "  grpo         = git prune remote and locals"
  echo "  grso         = git remote show origin"
  echo "  gcf          = git config --list"
  echo "  gm           = git pull, merge branch, push, status"
  echo "  gmt          = git merge theirs, push, status"

  echo "  gck          = git checkout, pull, status"
  echo "  gdbf         = git delete local and remote branch"
  echo "  gdb          = git delete local branch"
  echo "  gfc          = git fix last commit message"
  echo "  gpsvn        = find and delete .svn files"
  echo "  gclone       = run hough custom clone script"
  echo "  gs           = git status"
  echo "  gt           = git tag"
  echo "  gtl          = git tag -l"
  echo "  gct          = git set the tag and push it"
  echo "  gpot         = git push origin --tags"
  echo "  gpt          = git push --tags"
  echo "  gdt          = git delete tag"
  echo "  gl           = git log --show-notes"
  echo "  glt          = git log --graph --oneline --all"
  echo "  gltp         = git log --graph --all --decorate"
  echo "---------------------------------------------------------------"
  echo "  gk           = create git .keep file"
  echo "  gkf          = create folder with .keep file"
  echo "  gmd          = create readme markdown file"
  echo
}
