#!/bin/zsh
githelp () {
  echo
  echo "--------------------------------------------------------------------------------"
  echo "  gc           = commit locally, but do not push to origin"
  echo "  gs           = status of local files"
  echo "  gcb          = pull, create local branch, push it to origin, set upstream"
  echo "  gmb          = pull, merge branch, push, status"
  echo "  gmt          = pull, merge branch with full rewrite, push, status"
  echo "  gdb          = delete local and remote branch"
  echo "  gp           = pull down all the code and all the tags"
  echo "  gpo          = pushing all the things to origin"
  echo "  gck          = checkout, pull, status"
  echo "  gct          = set the tag and push it"
  echo "  gdt          = delete tag and push delete"
  echo "  grpo         = purge dead branches locally and origin"
  echo "  gcbn         = current branch name"
  echo "  gk           = create git .keep file"
  echo "  gkf          = create folder with .keep file"
  echo "  gcmd         = create readme markdown file and open it"
  echo "--------------------------------------------------------------------------------"
  echo "  gpt          = git push --tags"
  echo "  gl           = git log --show-notes"
  echo "  glt          = git log --graph --oneline --all"
  echo "  gltp         = git log --graph --all --decorate"






  echo "  gfmb         = git flow subcommand finish branch :: param 1= subcommand param 2=branch"
  echo "  gfcb         = git flow subcommand start branch :: param 1= subcommand param 2=branch"
  echo "  gfi          = setup code repo using gitflow"
  echo "  gfh          = git flow help"
  echo "  gf           = git flow"
  echo "  gcl          = git commit local, and status"
  echo "  gmdb         = git merge and delete branch everywhere"
  echo "  gd           = git diff"
  echo "  grso         = git remote show origin"
  echo "  gcf          = git config --list"
  echo "  gfc          = git fix last commit message"
  echo "  gpsvn        = find and delete .svn files"

  echo "  gt           = git tag"
  echo "  gtl          = git tag -l"
  echo "  gpot         = git push origin --tags"


  echo
}
