#!/bin/zsh
rubyhelp () {
  echo
  echo "--------------------------------------------------------------------------------"
  echo "  rb          = rbenv"
  echo "  rr          = bundle exec rake routes"
  echo "  rs          = rails server"
  echo "  rc          = rails console"
  echo "  rt          = rspec tests"
  echo "  rg          = rails generate"
  echo "  rdb         = rails db console"
  echo "  rbe         = run bundle exec"
  echo "  rgo         = find out which gems are outdated on the project"
  echo "  rbl         = rbenv install -l"
  echo "  rbi         = bundle install"
  echo "  rake        = noglob bundle exec rake"
  echo "--------------------------------------------------------------------------------"
  echo "  railsinit   = setup new rails application with postgres db and run bundler"
  echo "  rtail       = tails rails log, option param for log name"
  echo "--------------------------------------------------------------------------------"
  echo
}
