windows:
  - name: rbr_config
    layout: main-vertical
    panes:
      - commands:
        - clear
        - echo "Configurations Windows"
      - commands:
        - clear
        - cd $HOME/.myconfigurations
        - clear
      - commands:
        - clear
        - cd $HOME/Career/RobotsBuildingRobots/code/personal-branding/MyVersionedAssets
        - clear
      - commands:
        - clear
        - cd $HOME/Career/RobotsBuildingRobots/code/personal-branding/MyVersionedAssets
        - clear
      - commands:
        - clear
        - cd $HOME
        - clear
        - lsa
