windows:
  - name: rbr_application_framework
    layout: double-main-horizontal
    panes:
      - commands:
        - clear
        - cd $HOME/Career/RobotsBuildingRobots/code/application-factory
        - clear
      - commands:
        - clear
        - cd $HOME/Career/RobotsBuildingRobots/code/application-factory
        - clear
      - commands:
        - clear
        - cd $HOME/Career/RobotsBuildingRobots/code/application-factory
        - clear
      - commands:
        - clear
        - cd $HOME/Career/RobotsBuildingRobots/code/application-factory
        - clear
      - commands:
        - clear
        - cd $HOME/Career/RobotsBuildingRobots/code/application-factory
        - clear
