#!/bin/zsh
# ---------------------------------------------------------------
# Check In, Push, Status Check
function gitc() {
 git add . -A;
 git commit -m "$*";
 git push;
 git status;
}
# ---------------------------------------------------------------
# Merge, Push, Status Check
function gitm() {
 git merge "$*";
 git push;
 git status;
}
# ---------------------------------------------------------------
# Create Branch, Push to Git, Status Check
function gitcb() {
 git branch "$*";
 git push -u origin "$*";
 git push --set-upstream origin "$*";
 git status;
}
# ---------------------------------------------------------------
# Merge, Push, Status Check
function gitdb() {
 git branch -d "$*";
 git push --delete origin "$*";
 git fetch -p;
 git remote show origin;
 git status;
}
# ---------------------------------------------------------------
# Create .gitkeep
function gitk() {touch .keep}
function gitkf() {
 mkdir "$*";
 touch "$*/.keep";
}
# ---------------------------------------------------------------
# Create readme.md
function gitmd() {
 touch readme.md;
 open readme.md;
}
# ---------------------------------------------------------------
# Create readme.md
function gitdt() {
 git tag -d "$*";
 git push origin :refs/tags/"$*";
}
# ---------------------------------------------------------------
alias gitcl="git config --list"
alias gitclone="sh $HOME/.myconfigurations/git/scripts/clone.sh"

alias gitck="git checkout "
alias gitpull="git pull"

alias gitb="git branch"

alias gitp="git push"
alias gitpo="git push origin "
alias gitpb="git push  -u origin "
alias gitpot="git push origin --tags"
alias gitphm="git push heroku master"
alias gitpt="git push --tags"
alias gitpushall="git push --recurse-submodules=on-demand"

alias gits="git status"
alias gitt="git tag"
alias gitsh="git show"

alias gitl="git log --show-notes"
alias gitltree="git log --graph --oneline --all"
alias gitltreeb="git log --graph --all --decorate"

alias gitdf="git fetch -p"

alias gitrso="git remote show origin"
alias gitlsr="git ls-remote"
alias gitrv="git remote -v"

alias standup="git log --since '1 day ago' --no-merges --pretty=format':%C(yellow)%h %aN%n %B%n' --oneline --author 'Chris Hough'"
alias standup5="git log --since '5 day ago' --no-merges --pretty=format':%C(yellow)%h %aN%n %B%n' --oneline --author 'Chris Hough'"
alias standup10="git log --since '10 day ago' --no-merges --pretty=format':%C(yellow)%h %aN%n %B%n' --oneline --author 'Chris Hough'"

# ---------------------------------------------------------------
# Create .gitkeep
function gitpurgesvn() {
  find . -name .svn  -type d -print0 |xargs -0 rm -rf
}
