#!/bin/zsh
# ---------------------------------------------------------------
# Git Check In, Push, Status Check
function gitc() {
 git commit -m "$*";
 git push;
 git status;
}
# ---------------------------------------------------------------
# Git Merge, Push, Status Check
function gitm() {
 git merge "$*";
 git push;
 git status;
}
# ---------------------------------------------------------------
# Git Merge, Push, Status Check
function gitpb() {
 git push -u origin "$*";
 git status;
}
# ---------------------------------------------------------------
# Create .gitkeep
function gitk() {touch .keep}
function gitkf() {
 mkdir "$*";
 touch "$*/.keep";
}
# ---------------------------------------------------------------
alias gita="git add ."
alias gitad="git add . -A"
alias gitck="git checkout "
alias gitpull="git pull"
alias gitclone="sh $HOME/.myconfigurations/git/scripts/clone.sh"

alias gitp="git push"
alias gitpo="git push origin "
alias gitpot="git push origin --tags"
alias gitphm="git push heroku master"
alias gitpt="git push --tags"
alias gitpushall="git push --recurse-submodules=on-demand"

alias gitcl="git config --list"
alias gits="git status"
alias gitb="git branch"
alias gitt="git tag"
alias gitsh="git show"

alias gitl="git log --show-notes"
alias gitltree="git log --graph --oneline --all"
alias gitltreeb="git log --graph --all --decorate"

alias gitdr="git push --delete origin "
alias gitdb="git branch -d "
alias gitdt="git tag -d "

alias gitrso="git remote show origin"
alias gitrv="git remote -v"

alias standup="git log --since '1 day ago' --no-merges --pretty=format':%C(yellow)%h %aN%n %B%n' --oneline --author 'Chris Hough'"
alias standup5="git log --since '5 day ago' --no-merges --pretty=format':%C(yellow)%h %aN%n %B%n' --oneline --author 'Chris Hough'"
alias standup10="git log --since '10 day ago' --no-merges --pretty=format':%C(yellow)%h %aN%n %B%n' --oneline --author 'Chris Hough'"

alias purgeSVN="find . -name .svn  -type d -print0 |xargs -0 rm -rf;"
