#!/bin/zsh
# ---------------------------------------------------------------
# Git Check In, Push, Status Check
function gitch() {
 git commit -m "$*";
 git push;
 git push heroku master;
 git status;
}
# ---------------------------------------------------------------
# Git Push, Status Check
function gitph() {
 git push heroku master;
 git status;
}
# ---------------------------------------------------------------
alias h="heroku"
alias hlog="heroku logs"
alias hps="heroku ps"
alias hrr="heroku run rake "
alias hrc="heroku run rails console"
alias hc="heroku config"
alias ha="heroku apps"