#!/bin/zsh
# ---------------------------------------------------------------
# zsh rake processing
alias rake="noglob rake"
# ---------------------------------------------------------------
# Run Blog Locally
function buildblog() {
 purgeblog;
 rake generate;
}
# ---------------------------------------------------------------
# Run Blog Locally
function runblog() {
 purgeblog;
 rake generate;
 rake preview;
}
# ---------------------------------------------------------------
# Run Blog Locally
function purgeblog() {
 rm -rf "$myblog/public"
 rm -rf "$myblog/.gist-cache"
 rm -rf "$myblog/.instagram-cache"
 rm -rf "$myblog/.sass-cache"
 rm -rf "$myblog/.pygments-cache"
}
# ---------------------------------------------------------------
# Create a post anywhere
function newpost () {
	date=`date +%Y-%m-%d`
	echo "Creating a new post titled '$1'.";
	cd $myblog/;
	rake "new_post[$1]";
}
function newdraft () {
  date=`date +%Y-%m-%d`
  echo "Creating a new draft titled '$1'.";
  cd $myblog/;
  rake "new_draft[$1]";
}
