#!/bin/zsh
# ---------------------------------------------------------------
# Ruby Environment Commands
alias rb="rbenv"
alias rbuild="bundle install --path=.bundle --binstubs=.bundle/binstubs"
# ---------------------------------------------------------------
# Rails Rake Environment Commands
alias rk="rake"
# ---------------------------------------------------------------
# rbenv shortcuts
export PATH=".bundle/binstubs:$PATH" 
# ---------------------------------------------------------------
# List Gem Versions
function gemv() {
 gem list "$*" --remote --all;
}
