#!/bin/zsh
# ---------------------------------------------------------------
# Ruby Environment Commands
alias rb="rbenv"
alias rbuild="bundle install --path=.bundle --binstubs=.bundle/binstubs"
alias be="bundle exec"
# ---------------------------------------------------------------
# Rails Rake Environment Commands
alias rk="rake"
# ---------------------------------------------------------------
# Rails GenerateCommands
function rgc() {
  rails g controller "$*";
}
# ---------------------------------------------------------------
function rgcP() {
  rails g controller "$*";
}
# ---------------------------------------------------------------
function rgm() {
  rails g model "$*";
}
# ---------------------------------------------------------------
function rgmP() {
  rails g model "$*" --migration=false;
}
# ---------------------------------------------------------------
function rtail() {
  if [ "$*" != "" ]; then
    tail -f "log/$*.log";
  else
    tail -f log/development.log;
  fi
}
# ---------------------------------------------------------------
function rbuild() {
  bundle install --path=.bundle --binstubs=.bundle/binstubs;
}
# ---------------------------------------------------------------
# rbenv shortcuts
export PATH=".bundle/binstubs:$PATH" 
# ---------------------------------------------------------------
# List Gem Versions
function gemv() {
 gem list "$*" --remote --all;
}
