# Review the detailed rspec cops here!
# https://github.com/backus/rubocop-rspec

RSpec/NestedGroups:
  Max: 10

RSpec/AlignRightLetBrace:
  Enabled: false

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/Pending:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/DescribeMethod:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MultipleExpectations:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false
