#!/bin/zsh

function brewhelp () {
  echo
  echo "--------------------------------------------------------------------------------"
  echo
  echo "  bd           = brew doctor"
  echo "  bu           = brew update, brew upgrade, brew doctor"
  echo "  bsc          = brew services cleanup"
  echo "  bsl          = brew services list"
  echo
  echo "--------------------------------------------------------------------------------"
  echo
}

alias bd="brew doctor"
alias bsc="brew services cleanup"
alias bsl="brew services list"

function bu() {
  brew update
  brew upgrade
  brew doctor
}



