#!/bin/zsh

alias bd="brew doctor"
alias bsc="brew services cleanup"
alias bsl="brew services list"

function bu() {
  brew update
  brew upgrade
  brew doctor
}

function bsr() {
  bsx
  bss
}

function bsx() {
  brew services stop opensearch
  brew services stop mongodb-community
  brew services stop redis
  bsc
  bsl
}

function bss() {
  brew services start opensearch
  brew services start postgresql
  brew services start redis
  bsc
  bsl
}

function brewhelp () {
  echo
  echo "--------------------------------------------------------------------------------"
  echo
  echo "  bd           = brew doctor"
  echo "  bu           = brew update, brew upgrade, brew doctor"
  echo "  bsx          = stop all brew services"
  echo "  bss          = start all brew services"
  echo "  bsr          = restart all brew services"
  echo "  bsc          = brew services cleanup"
  echo "  bsl          = brew services list"
  echo
  echo "--------------------------------------------------------------------------------"
  echo
}
