#!/bin/zsh

# alias dvy="itermocil"

function dvy() {
  if [[ -n "$1" ]]; then
    itermocil "$1"
  else
    itermocil --list | grep -v "^/" | sort -V
  fi
}
function dvyl() { itermocil $(itermocil --list | grep -v "^/" | sort -Vr | fzf) }

function dvyhelp () {
  echo
  echo "--------------------------------------------------------------------------------"
  echo
  echo "  dvy          = launch itermocil"
  echo "  dvyl         = list itermocil profiles"
  echo
  echo "--------------------------------------------------------------------------------"
  echo
}

