#!/bin/zsh

alias dvy="itermocil"

function dvyl() { dvy --list | grep -v "^/" | sort -f }


function dvyhelp () {
  echo
  echo "--------------------------------------------------------------------------------"
  echo
  echo "  dvy          = launch itermocil"
  echo "  dvyl         = list itermocil profiles"
  echo
  echo "--------------------------------------------------------------------------------"
  echo
}

