#!/bin/zsh

function pghelp () {
  echo
  echo "--------------------------------------------------------------------------------"
  echo
  echo "  pgv           = database versions"
  echo
  echo "--------------------------------------------------------------------------------"
  echo
}

function pgv() {
  postgres -V;
  psql -V;
}



