#!/bin/zsh

# SETTINGS AND PRIVATE VARIABLES : NEVER CHECK IN THIS FILE!
source $HOME/.myconfigurations.private.keys

# ADJUST SHELL HISTORY
export HISTFILESIZE=10000
export HISTSIZE=10000
PROMPT_COMMAND='history -a'

# SET BROWSER FOR SHELL COMMANDS
export BROWSER='open -a /Applications/Google Chrome.app'

# DEFAULT EDITOR
export EDITOR=vim

# IMPORT FUNCTIONS GROUPS
_myconfig_modules=(ruby docker git brew python heroku js shell divvy ai)

for _module in "${_myconfig_modules[@]}"; do
  source "$HOME/.myconfigurations/dotfiles/functions/collections/$_module"
done

# CLEAN UP TEMPORARY VARIABLES
unset _myconfig_modules _module

# AUTOJUMP
export AUTOJUMP_IGNORE_CASE=1

# ZSH AUTOCOMPLETE
autoload -U compinit && compinit

if command -v brew &>/dev/null; then
  [[ -s $(brew --prefix)/etc/autojump.sh ]] && . $(brew --prefix)/etc/autojump.sh
fi

# ZSH HELP
function help() {
  echo
  echo "-------------------------------------------"
  echo
  echo "  brewhelp"
  echo "  dvyhelp"
  echo "  dkrhelp"
  echo "  herokuhelp"
  echo "  githelp"
  echo "  rubyhelp"
  echo "  shellhelp"
  echo
  echo "-------------------------------------------"
  echo
}
