#!/bin/zsh
_myconfig_modules=(itermocil brew python)

for _module in "${_myconfig_modules[@]}"; do
  source "$HOME/.myconfigurations/dotfiles/functions/collections/$_module"
done

# Clean up temporary variables
unset _myconfig_modules _module
