#!/bin/zsh
alias dpg="dotgpg"
alias bd="brew doctor"
alias dvy="itermocil"
alias vscode="code ."

function mc() { mailcatcher -f -v }
function openmd() { open -a "/Applications/Mou.app" "$1"; }

function bu() {
  brew update
  brew doctor
}
