#!/bin/zsh
# ---------------------------------------------------------------
alias mc="mailcatcher -f -v"
alias atom="atom ."
# ---------------------------------------------------------------

appshelp () {
  echo
  echo "  mc           = mailcatcher -f -v"
  echo
}
