#!/bin/zsh
# ---------------------------------------------------------------
alias kb="keybase"

# gets and installs the latest keybase
function kbi() {
 keybase-installer
}

# which version are you running
function kbv() {
 keybase version
}

# ---------------------------------------------------------------

keybasehelp () {
  echo
  echo "  kb           = keybase"
  echo "  kbi          = keybase installer"
  echo "  kbv          = keybase version"
  echo
}
