#!/bin/zsh
alias rb="rbenv"
alias rr="bundle exec rake routes"
alias rs="bundle exec ./bin/rails s"
alias rt="bundle exec ./bin/rspec"
alias rc="bundle exec ./bin/rails c"
alias rg="rails g"
alias rgo="gem outdated"
alias rbe="bundle exec"
alias rdb="rails dbconsole"
alias rbl="rbenv install -l"
alias rbi="bundle install"
alias rbibs="bundle install --path=.bundle --binstubs=.bundle/binstubs"
alias rake="noglob bundle exec rake"

function railsinit() {
  if [[ $1 ]]; then
    if [[ ! -d "$1" ]]; then
      msg "Creating project folder: $1"
      mkdir "$1"
    fi
    cd "$1"
    msg "Setup default ruby version!"
    rbenvset
    msg "Building a rails application with postgresql!"
    rails new . --skip-bundle -T --database=postgresql
    msg "Override rails gitignore and readme with better versions!"
    cp $HOME/.myconfigurations/software/git/templates/ignores/rails-application .gitignore
    if [[ -f "README.md" ]]; then
      rm README.md
    fi
    if [[ -f "README.rdoc" ]]; then
      rm README.rdoc
    fi
    cp $HOME/.myconfigurations/software/git/templates/readmes/rails-application readme.md
    msg "Using Bundler and setting up local binstubs!"
    bundle install --path=.bundle --binstubs=.bundle/binstubs
  else
    msg "ERROR! Missing project name!"
  fi
}
function rbenvset() {
  rbenv local $(rbenv global)
}
function rtail() {
  if [[ $1 ]]; then
    tail -f "log/$1.log";
  else
    tail -f log/development.log;
  fi
}
