#!/bin/zsh
MYRUBYVERSION="2.3.0"
export RUBY_DEP_GEM_SILENCE_WARNINGS=1
export BUNDLER_EDITOR="atom"

alias rb="rbenv"
alias rr="bundle exec rake routes"
alias rsp="bundle exec rescue ./bin/rails s"
alias rs="spring stop && bundle exec ./bin/rails s"
alias rt="spring stop && bundle exec ./bin/rspec"
alias rtc="bundle exec rescue ./bin/rspec"
alias rc="spring stop && bundle exec ./bin/rails c"
alias rg="rails g"
alias rgod="gem outdated"
alias rbe="bundle exec"
alias rdb="rails dbconsole"
alias rbl="rbenv install -l"
alias rbi="bundle install"
alias rbu="bundle update"
alias rbibs="bundle install --path=.bundle --binstubs=.bundle/binstubs"
alias rake="noglob bundle exec rake"
alias guard="bundle exec guard"

GEMDIR=.bundle/ruby/$MYRUBYVERSION/gems

function rgo() {
	LOCALGEM=$(find $GEMDIR -name \*$1\* -type d -maxdepth 1 -print | head -n1)
	atom $LOCALGEM
}
function railsinit() {
	if [[ ! -z "$1" ]]; then
		msg "Creating project folder: $1"
		mkdir "$1"
		cd "$1"
	fi
	msg "Setup default ruby version!"
	rbenvset
	msg "Building a rails application with postgresql!"
	rails new . --skip-bundle -T --database=postgresql
	msg "Override rails gitignore and readme with better versions!"
	cp $HOME/.myconfigurations/software/git/templates/ignores/rails-application .gitignore
	if [[ -f "README.md" ]]; then
		rm README.md
	fi
	if [[ -f "README.rdoc" ]]; then
		rm README.rdoc
	fi
	cp $HOME/.myconfigurations/software/git/templates/readmes/rails-application readme.md
	msg "Using Bundler and setting up local binstubs!"
	bundle install --path=.bundle --binstubs=.bundle/binstubs
}
function rbenvset() {
	rbenv local $(rbenv global)
}
function rbenvupdate {
	cd
	brew upgrade rbenv
	cd ~/.rbenv
	cd plugins
	for i in *
	do
		cd $i
		git pull
		cd -
	done
	cd
}
function rtail() {
	if [[ $1 ]]; then
		tail -f "log/$1.log";
	else
		tail -f log/development.log;
	fi
}
