#!/bin/zsh
alias upzsh="upgrade_oh_my_zsh"
alias dvy="itermocil"

function reloadshell() { exec $SHELL }
function getpwd() { pwd | pbcopy }
function flush() { sudo killall -HUP mDNSResponder }
function disc() { df -h }
function up() { uptime | sed -e "s/:/ /2" | sed -e "s/,/ /2" | awk '{print "Up " $3 " days, " $5 " hours and " $6 " minutes"}' }
function purgeSVN() { find . -name .svn  -type d -print0 |xargs -0 rm -rf }
function purgeDS() { find . -name '*.DS_Store' -type f -delete }

function hidefiles() {
  defaults write com.apple.finder AppleShowAllFiles NO;
  killall Finder /System/Library/CoreServices/Finder.app;
}
function showfiles() {
  defaults write com.apple.finder AppleShowAllFiles YES;
  killall Finder /System/Library/CoreServices/Finder.app;
}
function cls() {
  osascript -e 'tell application "System Events" to keystroke "k" using command down'
}
